#!/usr/bin/env python

import email
import re
import os
import sys
from tqdm import tqdm
import ayemappy
import getpass

def ensure_dir(file_path):
    directory = os.path.dirname(file_path)
    if not os.path.exists(directory):
        os.makedirs(directory)

def main():

    imapserver = raw_input('Enter the server name:')
    userName = raw_input('Enter your username:')
    passwd = getpass.getpass('Enter your password: ')

    M = ayemappy.Ayemappy(imapserver, userName, passwd)
    for folder in M.listfolders():
	print 'Processing %s' % folder

	# Iterating over all emails
        for msgId in tqdm(M.listmessages(folder)):
	    typ, messageParts = M.Session.fetch(msgId, '(RFC822)')
	    if typ != 'OK':
		print 'Error fetching mail.'
		raise

	    emailBody = messageParts[0][1]
	    mail = email.message_from_string(emailBody)
	    for part in mail.walk():
		if part.get_content_maintype() == 'multipart':
		    continue
		if part.get('Content-Disposition') is None:
		    continue
		fileName = part.get_filename()

		if bool(fileName):
		    filePath = os.path.join(".", M.server, M.user, fileName)
                    ensure_dir(filePath)
		    if not os.path.isfile(filePath) :
			print fileName
			fp = open(filePath, 'wb')
                        segment = part.get_payload(decode=True)
                        if segment:
			    fp.write(segment)
			fp.close()

if __name__ == '__main__':
    main()
